/******************************************************************************/
/***               Generated by IBExpert 14.12.2017 16:53:01                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_ZATR_MONEY_ID;

CREATE TABLE ZATR_MONEY (
    MONEY_ID          INTEGER NOT NULL,
    STRUK_ID          INTEGER,
    KSM_ID            INTEGER,
    KEI_ID            INTEGER,
    KSM_IDPR          INTEGER,
    NOMEN_MONEY       NUMERIC(18,6),
    OST_BEG_MONEY     NUMERIC(18,6),
    ZAGR_MONEY        NUMERIC(18,6),
    RASH_MONEY        NUMERIC(18,6),
    OST_END_MONEY     NUMERIC(18,6),
    MES               INTEGER,
    GOD               INTEGER,
    PF                INTEGER,
    DATE_TIME_UPDATE  TIMESTAMP,
    USER_NAME         CHAR(10),
    RAZDEL_ID         INTEGER,
    ACCOUNT           CHAR(5)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE ZATR_MONEY ADD CONSTRAINT PK_ZATR_MONEY PRIMARY KEY (MONEY_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: ZATR_MONEY_BI */
CREATE OR ALTER TRIGGER ZATR_MONEY_BI FOR ZATR_MONEY
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.money_id is null) then
    new.money_id = gen_id(gen_zatr_money_id,1);
end
^


/* Trigger: ZATR_MONEY_BIU0 */
CREATE OR ALTER TRIGGER ZATR_MONEY_BIU0 FOR ZATR_MONEY
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
begin
  new.date_time_update = current_timestamp;
  new.user_name = current_user;
end
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON ZATR_MONEY TO IGOR WITH GRANT OPTION;

/* Privileges of roles */
GRANT ALL ON ZATR_MONEY TO SKLAD_CEH;
GRANT ALL ON ZATR_MONEY TO SYSTEM;